"""Generate the frontend's build-time view of the real-data snapshot.

    python scripts/real_data/build_frontend_snapshot.py           write the file
    python scripts/real_data/build_frontend_snapshot.py --check   fail if it is stale

The frozen v1 API exposes no topology endpoint and none is added. Instead the
frontend imports this generated module - a plain projection of the VERIFIED
snapshot (data/railway/ndls_agc) - so the station/chainage tables, the
timetable that was used, the sources and the provenance labels shown in the UI
cannot drift from the data the backend loads. It carries no logic of its own.

The snapshot is loaded through backend.app.data.real_corridor_dataset, so this
refuses to generate from an altered or inconsistent snapshot.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from backend.app.data.real_corridor_dataset import (  # noqa: E402
    CANDIDATE_WINDOW_LABEL,
    load_real_snapshot,
)

OUTPUT = REPO_ROOT / "frontend" / "src" / "data" / "ndlsAgcSnapshot.generated.ts"

HEADER = """\
// GENERATED by scripts/real_data/build_frontend_snapshot.py from data/railway/ndls_agc.
// Do not edit by hand: backend/tests/test_real_snapshot.py fails if this file is stale.
//
// A build-time projection of the verified offline snapshot. The v1 API is frozen
// and serves no topology, so the UI reads its station/chainage tables, the
// timetable it was planned against, and its sources/provenance from here.
"""



def build_payload() -> Dict[str, Any]:
    snap = load_real_snapshot()
    topology = snap.topology
    timetable = snap.timetable

    stations = [
        {
            "id": s["station_id"],
            "name": s["name"],
            "km": s["km"],
            "kmDisplay": s["km_display"],
            "kmPrecision": s["km_precision"],
            "kmUncertaintyKm": s["km_uncertainty_km"],
            "lat": s["lat"],
            "lon": s["lon"],
        }
        for s in topology["stations"]
    ]

    sections = [
        {
            "id": s["section_id"],
            "start": s["start_station_id"],
            "end": s["end_station_id"],
            "kmStart": s["km_start"],
            "kmEnd": s["km_end"],
            "lengthKm": s["length_km"],
            "zone": s["zone"],
            "division": s["division"],
        }
        for s in topology["sections"]
    ]

    km_records = {
        r["field"].split(".")[1]: r for r in topology["provenance"] if r["field"].endswith(".km")
    }
    for station in stations:
        record = km_records[station["id"]]
        station["kmClass"] = record["class"]
        station["kmConfidence"] = record["confidence"]
        station["kmNote"] = record.get("note", "")

    sources = [
        {
            "id": s["source_id"],
            "name": s["name"],
            "publisher": s["publisher"],
            "url": s["url"],
            "type": s["source_type"],
            "dataAsOf": s["data_as_of"],
            "retrievedAt": s["retrieved_at"],
            "lastReviewed": s["last_reviewed"],
            "licence": s["licence"],
            "currency": s["currency"],
            "sha256": s["sha256"],
        }
        for s in snap.manifest["sources"]
        if not s["source_type"].startswith("DERIVED")
    ]

    trains: List[Dict[str, Any]] = []
    for t in timetable["trains"]:
        trains.append(
            {
                "number": t["train_number"],
                "name": t["train_name"],
                "from": t["from_station_name"],
                "to": t["to_station_name"],
                "direction": t["direction"],
                "days": t["days_of_departure_tag"],
                "stops": [
                    {
                        "station": s["station_id"],
                        "arr": s["tag_arrival"],
                        "dep": s["tag_departure"],
                    }
                    for s in t["published_stops"]
                ],
            }
        )

    works = [
        {
            "demoJobKey": g["demo_job_key"],
            "jobType": g["job_type"],
            "sectionId": g["section_id"],
            "summary": g["grounding_summary"],
            "items": [
                {"zone": i["zone"], "itemNo": i["item_no"], "page": i["pdf_page"], "text": i["text"]}
                for i in g["grounding_items"]
            ],
        }
        for g in snap.works["demo_job_grounding"]
    ]

    blocks = []
    for b in snap.blocks["blocks"]:
        blocks.append(
            {
                "id": b["block_id"],
                "kind": b["kind"],
                "location": b["location"],
                "from": b["period_from"],
                "to": b["period_to"],
                "status": b["status_at_retrieval"],
                "class": b["class"],
                "usedInDerivation": b["used_in_derivation"],
                "note": b.get("scope_note") or b.get("period_note") or "",
            }
        )

    infrastructure = {
        "kmPosts": [
            {"place": k["place"], "km": k["km_post"], "asOf": k["document_date"], "class": k["class"]}
            for k in snap.infrastructure["kilometre_posts"]
        ],
        "runningLines": [
            {"location": l["location"], "lines": l["running_lines"], "count": l["count"], "asOf": l["document_date"]}
            for l in snap.infrastructure["running_lines"]
        ],
        "automaticSignalling": [a["section"] for a in snap.infrastructure["automatic_signalling_sections"]],
        "kavach": [{"section": k["section"], "date": k["date"]} for k in snap.infrastructure["kavach"]],
        "levelCrossings": len(snap.infrastructure["level_crossings"]),
    }

    return {
        "snapshotId": snap.snapshot_id,
        "corridorId": snap.corridor_id,
        "retrievedAt": snap.manifest["retrieved_at"],
        "distanceUnit": topology["distance_unit"],
        "chainageOrigin": topology["chainage_origin"],
        "corridorName": topology["name"],
        "zone": topology["zone"],
        "division": topology["division"],
        "tracks": {
            t["track_id"]: {"direction": t["direction"], "meaning": topology["direction_convention"]["track_ids"][t["track_id"]]}
            for t in topology["tracks"]
        },
        "directionConvention": topology["direction_convention"],
        "stations": stations,
        "sections": sections,
        "sources": sources,
        "timetable": {
            "title": timetable["publication"]["title"],
            "effective": timetable["publication"]["effective"],
            "horizonDates": timetable["coverage"]["horizon_dates"],
            "trainCount": timetable["coverage"]["ingested_trains"],
            "notIncluded": timetable["coverage"]["not_included"],
            "label": timetable["coverage"]["label"],
            "trains": trains,
        },
        "possession": {
            "label": CANDIDATE_WINDOW_LABEL,
            "rules": snap.rules["engineering_rules"],
        },
        "works": works,
        "worksWording": snap.works["demo_job_grounding"][0]["wording"],
        "blocks": blocks,
        "infrastructure": infrastructure,
        "statement": snap.manifest["statement"],
    }


def render() -> str:
    payload = json.dumps(build_payload(), indent=2, ensure_ascii=False)
    return (
        HEADER
        + "\nexport const SNAPSHOT = "
        + payload
        + " as const;\n\nexport type Snapshot = typeof SNAPSHOT;\n"
    )


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    text = render()

    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != text:
            print("frontend snapshot is out of date")
            return 1
        print("frontend snapshot is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote", OUTPUT.relative_to(REPO_ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
