// GENERATED by scripts/real_data/build_frontend_snapshot.py from data/railway/ndls_agc.
// Do not edit by hand: backend/tests/test_real_snapshot.py fails if this file is stale.
//
// A build-time projection of the verified offline snapshot. The v1 API is frozen
// and serves no topology, so the UI reads its station/chainage tables, the
// timetable it was planned against, and its sources/provenance from here.

export const SNAPSHOT = {
  "snapshotId": "ndls-agc-2026-09-26",
  "corridorId": "CORR-NDLS-AGC",
  "retrievedAt": "2026-09-26",
  "distanceUnit": "km",
  "chainageOrigin": "NDLS = 0 km (derived origin). Chainage is NDLS-relative, not the railway's own km-post.",
  "corridorName": "New Delhi - Agra Cantt. (via Hazrat Nizamuddin, Faridabad, Palwal, Mathura Jn., Raja Ki Mandi)",
  "zone": "Northern Railway (NDLS-PWL) / North Central Railway (PWL-AGC)",
  "division": "Delhi Division (NDLS-PWL) / Agra Division (PWL-AGC)",
  "tracks": {
    "UP-1": {
      "direction": "UP",
      "meaning": "Up line - trains running NDLS -> AGC (official UP)."
    },
    "DOWN-1": {
      "direction": "DOWN",
      "meaning": "Down line - trains running AGC -> NDLS (official DN)."
    }
  },
  "directionConvention": {
    "UP": "Away from Delhi: NDLS -> AGC.",
    "DOWN": "Toward Delhi: AGC -> NDLS.",
    "track_ids": {
      "UP-1": "Up line - trains running NDLS -> AGC (official UP).",
      "DOWN-1": "Down line - trains running AGC -> NDLS (official DN)."
    },
    "note": "The synthetic fallback dataset uses the opposite meaning for the same identifiers (NDLS->AGC as DOWN-1). Identifiers are kept for contract stability; their meaning is stated per dataset."
  },
  "stations": [
    {
      "id": "NDLS",
      "name": "New Delhi",
      "km": 0.0,
      "kmDisplay": "0",
      "kmPrecision": "derived_origin",
      "kmUncertaintyKm": 0.0,
      "lat": 28.6434826,
      "lon": 77.2227421,
      "kmClass": "DERIVED_FROM_REAL",
      "kmConfidence": "high",
      "kmNote": ""
    },
    {
      "id": "NZM",
      "name": "Hazrat Nizamuddin",
      "km": 7.0,
      "kmDisplay": "7",
      "kmPrecision": "published_integer_km",
      "kmUncertaintyKm": 1.0,
      "lat": 28.5889646,
      "lon": 77.2535202,
      "kmClass": "DERIVED_FROM_REAL",
      "kmConfidence": "medium",
      "kmNote": "Whole kilometres only; +/-1 km."
    },
    {
      "id": "FDB",
      "name": "Faridabad",
      "km": 28.0,
      "kmDisplay": "28",
      "kmPrecision": "published_integer_km",
      "kmUncertaintyKm": 1.0,
      "lat": 28.4107617,
      "lon": 77.3070774,
      "kmClass": "DERIVED_FROM_REAL",
      "kmConfidence": "medium",
      "kmNote": "Whole kilometres only; +/-1 km."
    },
    {
      "id": "PWL",
      "name": "Palwal",
      "km": 54.8,
      "kmDisplay": "~54.8",
      "kmPrecision": "derived_from_official_kmposts",
      "kmUncertaintyKm": 3.0,
      "lat": 28.1515806,
      "lon": 77.3417952,
      "kmClass": "DERIVED_FROM_REAL",
      "kmConfidence": "low",
      "kmNote": "UNRESOLVED CONFLICT: the previously used unsourced value was ~57. The official chain gives the PWL-MTJ distance as ~86.23 km, i.e. ~54.8 km from NDLS. The Rundhi SIP text '(PALWAL SPL CLASS AT Km 9.31)' is read as the Rundhi-Palwal distance. Shown as '~54.8'."
    },
    {
      "id": "MTJ",
      "name": "Mathura Junction",
      "km": 141.0,
      "kmDisplay": "141",
      "kmPrecision": "published_integer_km",
      "kmUncertaintyKm": 1.0,
      "lat": 27.4801125,
      "lon": 77.6737596,
      "kmClass": "DERIVED_FROM_REAL",
      "kmConfidence": "medium",
      "kmNote": "TAG T-2 prints 145 (=> 142); T-3 prints 144 (=> 141). +/-1 km. The official km-post 1397.06 is Mumbai-origin, not comparable to the NDLS-relative value."
    },
    {
      "id": "RKM",
      "name": "Raja Ki Mandi",
      "km": 190.9,
      "kmDisplay": "~190.9",
      "kmPrecision": "derived_from_official_kmposts",
      "kmUncertaintyKm": 2.0,
      "lat": 27.1940261,
      "lon": 77.9970749,
      "kmClass": "DERIVED_FROM_REAL",
      "kmConfidence": "low",
      "kmNote": "Mixes a 2025 km-post with a 2012 SIP distance (read visually). TAG's own whole-km figure implies ~192; difference recorded in km_uncertainty_km."
    },
    {
      "id": "AGC",
      "name": "Agra Cantt.",
      "km": 194.8,
      "kmDisplay": "~194.8",
      "kmPrecision": "derived_from_official_kmposts",
      "kmUncertaintyKm": 2.0,
      "lat": 27.1589527,
      "lon": 77.9900478,
      "kmClass": "DERIVED_FROM_REAL",
      "kmConfidence": "low",
      "kmNote": "The AGC SIP prints Km 1343.5 and 1344.100 for yard features, consistent with ~1343.3."
    }
  ],
  "sections": [
    {
      "id": "NDLS-NZM",
      "start": "NDLS",
      "end": "NZM",
      "kmStart": 0.0,
      "kmEnd": 7.0,
      "lengthKm": 7.0,
      "zone": "Northern Railway",
      "division": "Delhi Division"
    },
    {
      "id": "NZM-FDB",
      "start": "NZM",
      "end": "FDB",
      "kmStart": 7.0,
      "kmEnd": 28.0,
      "lengthKm": 21.0,
      "zone": "Northern Railway",
      "division": "Delhi Division"
    },
    {
      "id": "FDB-PWL",
      "start": "FDB",
      "end": "PWL",
      "kmStart": 28.0,
      "kmEnd": 54.8,
      "lengthKm": 26.8,
      "zone": "Northern Railway",
      "division": "Delhi Division"
    },
    {
      "id": "PWL-MTJ",
      "start": "PWL",
      "end": "MTJ",
      "kmStart": 54.8,
      "kmEnd": 141.0,
      "lengthKm": 86.2,
      "zone": "North Central Railway",
      "division": "Agra Division"
    },
    {
      "id": "MTJ-RKM",
      "start": "MTJ",
      "end": "RKM",
      "kmStart": 141.0,
      "kmEnd": 190.9,
      "lengthKm": 49.9,
      "zone": "North Central Railway",
      "division": "Agra Division"
    },
    {
      "id": "RKM-AGC",
      "start": "RKM",
      "end": "AGC",
      "kmStart": 190.9,
      "kmEnd": 194.8,
      "lengthKm": 3.9,
      "zone": "North Central Railway",
      "division": "Agra Division"
    }
  ],
  "sources": [
    {
      "id": "SRC-TAG-2026-T2",
      "name": "Indian Railways Trains at a Glance 2026 - Table T-2 (New Delhi-Agra Cantt.-Bhopal-Bhusaval-CSMT)",
      "publisher": "Ministry of Railways, Railway Board (Coaching Directorate)",
      "url": "https://indianrailways.gov.in/railwayboard/uploads/directorate/coaching/TAG_2026/2.pdf",
      "type": "OFFICIAL_TIMETABLE_PDF",
      "dataAsOf": "2026-01-01",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-01-01",
      "licence": "Not stated in the document. Public Government of India publication, freely downloadable.",
      "currency": "Current edition as of the retrieval date; nine months old (does not reflect later notices).",
      "sha256": "7b997c53d620814d0c66b4e5aad53ac095a335da231f5ae674f94528814cadfa"
    },
    {
      "id": "SRC-NR-FDB-NOTICE",
      "name": "Northern Railway notice 31-08-2026: Cancellation/Regulation/Stoppage Skipping/Change in Platform of trains (Faridabad power and traffic block)",
      "publisher": "Northern Railway (Indian Railways portal)",
      "url": "https://nr.indianrailways.gov.in/view_detail.jsp?lang=0&id=0,4,268&dcd=13026",
      "type": "OFFICIAL_PRESS_RELEASE_TEXT",
      "dataAsOf": "2026-08-31",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-08-31",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Current.",
      "sha256": "702883e6b77e50da94f8977c821124e8d7ab8538a8c72c2e1e57d3f45b8f2a56"
    },
    {
      "id": "SRC-NR-FDB-ANNEX",
      "name": "Northern Railway Annexure-A: change in platform at Faridabad (43 trains with WTT and PTT times at FDB)",
      "publisher": "Northern Railway, Delhi Division",
      "url": "https://nr.indianrailways.gov.in/uploads/files/1788153462476-Platform%20change%20at%20FDB.pdf",
      "type": "OFFICIAL_NOTICE_PDF",
      "dataAsOf": "2026-08-27",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-08-31",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Current; PDF created 2026-08-27.",
      "sha256": "ca07a04b1a2b0776b849be3c279ad7563b172b63b0a3c9deb441aa5cb9d6f350"
    },
    {
      "id": "SRC-NCR-SIP-INDEX",
      "name": "NCR Agra Division S&T page listing Signal Interlocking Plans (AGC to PWL)",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/view_section.jsp?lang=0&id=0,1,283,375,704,707",
      "type": "OFFICIAL_WEB_PAGE_INDEX",
      "dataAsOf": "2026-09-09",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Page last reviewed 09-09-2026; the SIP documents themselves carry their own (older) dates.",
      "sha256": "e6110a0eb4fd14ad5c0bb8aa434651495abcb31fe301d9008090e794e470433d"
    },
    {
      "id": "SRC-NCR-SIP-RKM",
      "name": "NCR SIP - Raja Ki Mandi (EI), drawing 'S.I.PA1202 REV A' dated 20-03-2012",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1482128948114-002RAJA-KI-MANDI(EI)-Model.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2012-03-20",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "HISTORICAL (2012). Must not be read as the current infrastructure.",
      "sha256": "937dcbdfc71ff0c355a49ca817e801fb0abf76471e09bfd5367e31be98ca242a"
    },
    {
      "id": "SRC-NCR-SIP-AGC",
      "name": "NCR SIP - Agra Cantt.",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1482128923639-001agrs%20cantt-Model.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2016-12-14",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "HISTORICAL (file date 2016).",
      "sha256": "e29f14886a180f92af283854b932aca4fe400bc343008cf37c4fdbabe526bcb0"
    },
    {
      "id": "SRC-NCR-SIP-RUNAKTA",
      "name": "NCR SIP - Runakta (mini diagram, updated 09-10-2025)",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1761911811332-RNKA MINI UPDATED 091025.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2025-10-09",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Dated 2025-10.",
      "sha256": "c9c6f5674c1941d00d9411071d7a02451b322ecc3c38567297c79637b1d6b0f6"
    },
    {
      "id": "SRC-NCR-SIP-KITHAM",
      "name": "NCR SIP - Kitham (mini diagram 14-10-2025)",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1761911878914-KXM MINI 141025.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2025-10-14",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Dated 2025-10.",
      "sha256": "61492a03b7b394048d50da6fd547d8b06111be1827eff6df5a536db3a261143b"
    },
    {
      "id": "SRC-NCR-SIP-KITHAM-FARAH",
      "name": "NCR SIP - Kitham-Farah block section (mini diagram 14-10-2025)",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1761911920197-KXM-FAR MINI 141025.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2025-10-14",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Dated 2025-10.",
      "sha256": "8aecc94c6718bf357e732c489c4271e1588d38e17e2013699f643f12d81deb37"
    },
    {
      "id": "SRC-NCR-SIP-FARAH",
      "name": "NCR SIP - Farah (14-10-2025)",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1761911954548-FAR SIP 141025.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2025-10-14",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Dated 2025-10.",
      "sha256": "7fb656bf727d2ff76fa0040273f4896f3460b30c69871ab6ddda2d38b539d37e"
    },
    {
      "id": "SRC-NCR-SIP-FARAH-BAD",
      "name": "NCR SIP - Farah-Bad block section (mini diagram 14-10-2025)",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1761911993838-FAR-BAD MINI 141025.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2025-10-14",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Dated 2025-10.",
      "sha256": "15f1f2b5bba44a522fa25c3d79630b80618894e8cb38aac7ea3fe7a3a7d04fad"
    },
    {
      "id": "SRC-NCR-SIP-BAD",
      "name": "NCR SIP - Bad (24-10-2025)",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1761912054814-BAD MINI PH-2 UPDATED.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2025-10-24",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Dated 2025-10. Its station-building km (1386/797.85) differs by 42 m from the 1386.84 chainage printed in the Farah SIP.",
      "sha256": "9c512ea18fb76ad63a7a64853f4afbc1e0bfab57d2ac17cccf2d810c16a2d8cb"
    },
    {
      "id": "SRC-NCR-SIP-MTJ",
      "name": "NCR SIP - Mathura Junction",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1505826510056-008MATHURA JUNCTION-Model.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2017-09-04",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "HISTORICAL (file date 2017); the yard is being remodelled (see blocks.json).",
      "sha256": "1137d34f241fea99e635bb09a3d2371b0f77c728a06c3afef2950f3051510f6d"
    },
    {
      "id": "SRC-NCR-SIP-HODAL",
      "name": "NCR SIP - Hodal (2021)",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1642597291762-025 HODAL EI-Model.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2021-12-03",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Dated 2021 (file date).",
      "sha256": "df1f259f01dc7d1858249b631aa559407319221b5514324ba310a2661a350544"
    },
    {
      "id": "SRC-NCR-SIP-SHOLAKA-RUNDHI",
      "name": "NCR SIP - Sholaka-Rundhi block section (automatic signalling, 2021)",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1642597340820-028 AUTO SHOLAKA RUNDHI-Model.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2021-12-03",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Dated 2021 (file date).",
      "sha256": "59216d655bdab054f597a874d2237f3e2f4fc2a23095913740fd71462415af8f"
    },
    {
      "id": "SRC-NCR-SIP-RUNDHI",
      "name": "NCR SIP - Rundhi (2021)",
      "publisher": "North Central Railway, Agra Division",
      "url": "https://ncr.indianrailways.gov.in/uploads/files/1642597354636-029 RUNDHI EI-Model.pdf",
      "type": "OFFICIAL_SIGNAL_INTERLOCKING_PLAN",
      "dataAsOf": "2021-12-03",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "Dated 2021 (file date).",
      "sha256": "faaec43f5cc9481e2d01dc31cf27542af0568cc426772131132bc550c48ad977"
    },
    {
      "id": "SRC-OSM-STATIONS",
      "name": "OpenStreetMap station nodes (Overpass API), 7 corridor stations",
      "publisher": "OpenStreetMap contributors",
      "url": "https://overpass-api.de/api/interpreter",
      "type": "COMMUNITY_MAP_DATABASE",
      "dataAsOf": "2026-09-26T09:31:05Z",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-26",
      "licence": "Open Database Licence (ODbL) 1.0. Attribution: (c) OpenStreetMap contributors. Derived databases must stay under ODbL.",
      "currency": "Database timestamp 2026-09-26T09:31:05Z.",
      "sha256": "0c446896e224b47554f9c6a5686e7e478e12747c0aebf941487e8abed8c89e1a"
    },
    {
      "id": "SRC-CBS-2026-27",
      "name": "Consolidated Budget Statement 2026-27 (Pink Book new format) - North Central Railway and Northern Railway, excerpts",
      "publisher": "Ministry of Railways, Railway Board (Finance/Budget)",
      "url": "https://indianrailways.gov.in/railwayboard/uploads/directorate/finance_budget/CBS_2026-27/",
      "type": "OFFICIAL_BUDGET_DOCUMENT_EXCERPT",
      "dataAsOf": "2026-02-04",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-26",
      "licence": "Not stated. Public Government of India publication. Full PDFs (17 MB each) are NOT stored; their SHA-256 is recorded inside the excerpt file.",
      "currency": "PDF modified 2026-02-04.",
      "sha256": "3ab870f224a92fe0661a7bc08e03c1ee37269a7f1aa459ec76ae1744dd714611"
    },
    {
      "id": "SRC-PIB-KAVACH",
      "name": "PIB releases on Kavach 4.0 commissioning (2025-07-30, 2025-12-05, 2026-01-30), excerpts",
      "publisher": "Press Information Bureau, Government of India",
      "url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2221011",
      "type": "OFFICIAL_PRESS_RELEASE_EXCERPT",
      "dataAsOf": "2026-01-30",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-26",
      "licence": "Not stated. Public Government of India press releases.",
      "currency": "Latest release 2026-01-30.",
      "sha256": "e69c4c68a00494b4122354d22698a2563fdeafc3e410c18e53cb3e7a0bd0cfa3"
    },
    {
      "id": "SRC-CR-MTJ-2024",
      "name": "Central Railway notice 09-01-2024: cancellation/diversion due to non-interlocking work for yard remodelling at Mathura Junction",
      "publisher": "Central Railway (Indian Railways portal)",
      "url": "https://cr.indianrailways.gov.in/view_detail.jsp?lang=0&id=0,4,268&dcd=9099",
      "type": "OFFICIAL_PRESS_RELEASE_TEXT",
      "dataAsOf": "2024-01-09",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2024-01-09",
      "licence": "Not stated. Public Government of India portal.",
      "currency": "HISTORICAL (January-February 2024).",
      "sha256": "9a9ef41ff53c2f1e9707b088f635bacbbadf7ce70a4bbc286c562575bceca67d"
    },
    {
      "id": "SRC-PIB-2022-CORRIDOR-BLOCK",
      "name": "PIB 2022 (PRID 1863836): fixed corridor blocks of 3 hours in divisional working timetables (policy statement)",
      "publisher": "Press Information Bureau, Government of India",
      "url": "https://pib.gov.in/PressReleasePage.aspx?PRID=1863836",
      "type": "OFFICIAL_PRESS_RELEASE_EXCERPT",
      "dataAsOf": "2022-10-01",
      "retrievedAt": "2026-09-26",
      "lastReviewed": "2026-09-26",
      "licence": "Not stated. Public Government of India press release.",
      "currency": "2022.",
      "sha256": "c2860a274bc4960728483fb0b89edc86a4f9e0e393f5b661d6709838d229fd1e"
    }
  ],
  "timetable": {
    "title": "Indian Railways Trains at a Glance 2026, Table T-2",
    "effective": "2026-01-01",
    "horizonDates": [
      "2026-09-10",
      "2026-09-11"
    ],
    "trainCount": 23,
    "notIncluded": [
      "Trains listed only in other TAG tables (T-3, T-8, T-9, ...) that also use NDLS-MTJ or PWL-MTJ",
      "EMU/MEMU/local trains (the 64xxx services named in Northern Railway notices)",
      "Freight and light-engine/departmental movements",
      "The working timetable (WTT) and any as-run movements",
      "Notices after 2026-01-01 other than the Faridabad block, which is not applied to the timetable"
    ],
    "label": "Public passenger timetable subset. NOT complete corridor occupancy.",
    "trains": [
      {
        "number": "12138",
        "name": "Punjab Mail",
        "from": "Firozpur",
        "to": "Mumbai CSMT",
        "direction": "UP",
        "days": "Daily",
        "stops": [
          {
            "station": "NDLS",
            "arr": "04.55",
            "dep": "05.10"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "05.40"
          },
          {
            "station": "MTJ",
            "arr": "07.23",
            "dep": "07.28"
          },
          {
            "station": "RKM",
            "arr": null,
            "dep": "07.50"
          },
          {
            "station": "AGC",
            "arr": "08.10",
            "dep": "08.15"
          }
        ]
      },
      {
        "number": "12002",
        "name": "Shatabdi",
        "from": "New Delhi",
        "to": "Rani Kamalapati",
        "direction": "UP",
        "days": "Daily",
        "stops": [
          {
            "station": "NDLS",
            "arr": "06.00",
            "dep": null
          },
          {
            "station": "MTJ",
            "arr": "07.19",
            "dep": "07.20"
          },
          {
            "station": "AGC",
            "arr": "07.50",
            "dep": "07.55"
          }
        ]
      },
      {
        "number": "12280",
        "name": "Taj Express",
        "from": "New Delhi",
        "to": "Virangana Laxmibai Jhansi",
        "direction": "UP",
        "days": "Daily",
        "stops": [
          {
            "station": "NDLS",
            "arr": "06.55",
            "dep": null
          },
          {
            "station": "NZM",
            "arr": "07.06",
            "dep": "07.08"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "07.26"
          },
          {
            "station": "MTJ",
            "arr": "08.35",
            "dep": "08.40"
          },
          {
            "station": "RKM",
            "arr": null,
            "dep": "09.10"
          },
          {
            "station": "AGC",
            "arr": "09.25",
            "dep": "09.30"
          }
        ]
      },
      {
        "number": "12050",
        "name": "Gatiman Express",
        "from": "Nizamuddin",
        "to": "Virangana Laxmibai Jhansi",
        "direction": "UP",
        "days": "Except F",
        "stops": [
          {
            "station": "NZM",
            "arr": "08.10",
            "dep": null
          },
          {
            "station": "AGC",
            "arr": "09.50",
            "dep": "09.55"
          }
        ]
      },
      {
        "number": "12618",
        "name": "Mangala Lakshadweep Express",
        "from": "Nizamuddin",
        "to": "Ernakulam",
        "direction": "UP",
        "days": "Daily",
        "stops": [
          {
            "station": "NZM",
            "arr": "05.35",
            "dep": null
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "05.52"
          },
          {
            "station": "MTJ",
            "arr": "07.40",
            "dep": "07.45"
          },
          {
            "station": "AGC",
            "arr": "08.20",
            "dep": "08.25"
          }
        ]
      },
      {
        "number": "12406",
        "name": "Gondwana Express",
        "from": "Nizamuddin",
        "to": "Bhusaval",
        "direction": "UP",
        "days": "F,Su",
        "stops": [
          {
            "station": "NZM",
            "arr": "15.05",
            "dep": null
          },
          {
            "station": "MTJ",
            "arr": "16.25",
            "dep": "16.27"
          },
          {
            "station": "AGC",
            "arr": "17.15",
            "dep": "17.20"
          }
        ]
      },
      {
        "number": "14212",
        "name": "Intercity",
        "from": "New Delhi",
        "to": "Agra Cantt.",
        "direction": "UP",
        "days": "Daily",
        "stops": [
          {
            "station": "NDLS",
            "arr": "17.40",
            "dep": null
          },
          {
            "station": "NZM",
            "arr": "18.00",
            "dep": "18.01"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "18.25"
          },
          {
            "station": "MTJ",
            "arr": "20.13",
            "dep": "20.18"
          },
          {
            "station": "RKM",
            "arr": null,
            "dep": "21.05"
          },
          {
            "station": "AGC",
            "arr": "22.05",
            "dep": null
          }
        ]
      },
      {
        "number": "11058",
        "name": "Express",
        "from": "Amritsar",
        "to": "Mumbai CSMT",
        "direction": "UP",
        "days": "Daily",
        "stops": [
          {
            "station": "NDLS",
            "arr": "20.25",
            "dep": "20.40"
          },
          {
            "station": "NZM",
            "arr": "20.51",
            "dep": "20.53"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "21.12"
          },
          {
            "station": "MTJ",
            "arr": "22.50",
            "dep": "22.55"
          },
          {
            "station": "AGC",
            "arr": "23.45",
            "dep": "23.50"
          }
        ]
      },
      {
        "number": "12156",
        "name": "Bhopal Express",
        "from": "Nizamuddin",
        "to": "Rani Kamalapati",
        "direction": "UP",
        "days": "Daily",
        "stops": [
          {
            "station": "NZM",
            "arr": "20.40",
            "dep": null
          },
          {
            "station": "AGC",
            "arr": "22.38",
            "dep": "22.40"
          }
        ]
      },
      {
        "number": "11842",
        "name": "Express",
        "from": "Kurukshetra Jn.",
        "to": "Khajuraho Jn.",
        "direction": "UP",
        "days": "Daily",
        "stops": [
          {
            "station": "NDLS",
            "arr": "18.05",
            "dep": "18.20"
          },
          {
            "station": "NZM",
            "arr": "18.31",
            "dep": "18.33"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "18.52"
          },
          {
            "station": "MTJ",
            "arr": "20.35",
            "dep": "20.40"
          },
          {
            "station": "AGC",
            "arr": "21.25",
            "dep": "21.30"
          }
        ]
      },
      {
        "number": "22222",
        "name": "Rajdhani Express",
        "from": "Nizamudin",
        "to": "Mumbai CSMT",
        "direction": "UP",
        "days": "Daily",
        "stops": [
          {
            "station": "NZM",
            "arr": "16.55",
            "dep": null
          },
          {
            "station": "AGC",
            "arr": "18.45",
            "dep": "18.47"
          }
        ]
      },
      {
        "number": "20172",
        "name": "Vande Bharat Express",
        "from": "Nizamuddin",
        "to": "Rani Kamalapati",
        "direction": "UP",
        "days": "Except Sa",
        "stops": [
          {
            "station": "NZM",
            "arr": "14.40",
            "dep": null
          },
          {
            "station": "AGC",
            "arr": "16.16",
            "dep": "16.20"
          }
        ]
      },
      {
        "number": "14211",
        "name": "Intercity Express",
        "from": "Agra Cantt.",
        "to": "New Delhi",
        "direction": "DN",
        "days": "Daily",
        "stops": [
          {
            "station": "AGC",
            "arr": "05.45",
            "dep": null
          },
          {
            "station": "RKM",
            "arr": null,
            "dep": "05.53"
          },
          {
            "station": "MTJ",
            "arr": "06.20",
            "dep": "06.25"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "08.51"
          },
          {
            "station": "NZM",
            "arr": "09.15",
            "dep": "09.17"
          },
          {
            "station": "NDLS",
            "arr": "10.00",
            "dep": null
          }
        ]
      },
      {
        "number": "12617",
        "name": "Mangala Lakshadweep Express",
        "from": "Ernakulam",
        "to": "Nizamuddin",
        "direction": "DN",
        "days": "Daily",
        "stops": [
          {
            "station": "AGC",
            "arr": "09.55",
            "dep": "10.00"
          },
          {
            "station": "MTJ",
            "arr": "10.33",
            "dep": "10.38"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "12.50"
          },
          {
            "station": "NZM",
            "arr": "13.35",
            "dep": null
          }
        ]
      },
      {
        "number": "12049",
        "name": "Gatiman Express",
        "from": "Virangana Laxmibai Jhansi",
        "to": "Nizamuddin",
        "direction": "DN",
        "days": "Except F",
        "stops": [
          {
            "station": "AGC",
            "arr": "17.30",
            "dep": "17.35"
          },
          {
            "station": "NZM",
            "arr": "19.30",
            "dep": null
          }
        ]
      },
      {
        "number": "12137",
        "name": "Punjab Mail",
        "from": "Mumbai CSMT",
        "to": "Firozpur",
        "direction": "DN",
        "days": "Daily",
        "stops": [
          {
            "station": "AGC",
            "arr": "18.00",
            "dep": "18.05"
          },
          {
            "station": "RKM",
            "arr": null,
            "dep": "18.13"
          },
          {
            "station": "MTJ",
            "arr": "18.45",
            "dep": "18.50"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "20.35"
          },
          {
            "station": "NZM",
            "arr": "20.55",
            "dep": "20.57"
          },
          {
            "station": "NDLS",
            "arr": "21.25",
            "dep": "21.40"
          }
        ]
      },
      {
        "number": "12279",
        "name": "Taj Express",
        "from": "Virangana Laxmibai Jhansi",
        "to": "New Delhi",
        "direction": "DN",
        "days": "Daily",
        "stops": [
          {
            "station": "AGC",
            "arr": "18.15",
            "dep": "18.20"
          },
          {
            "station": "RKM",
            "arr": null,
            "dep": "18.28"
          },
          {
            "station": "MTJ",
            "arr": "19.00",
            "dep": "19.05"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "20.45"
          },
          {
            "station": "NZM",
            "arr": "21.05",
            "dep": "21.07"
          },
          {
            "station": "NDLS",
            "arr": "21.35",
            "dep": null
          }
        ]
      },
      {
        "number": "12001",
        "name": "Shatabdi Express",
        "from": "Rani Kamlapati",
        "to": "New Delhi",
        "direction": "DN",
        "days": "Daily",
        "stops": [
          {
            "station": "AGC",
            "arr": "21.20",
            "dep": "21.25"
          },
          {
            "station": "MTJ",
            "arr": "22.00",
            "dep": "22.01"
          },
          {
            "station": "NDLS",
            "arr": "23.50",
            "dep": null
          }
        ]
      },
      {
        "number": "11057",
        "name": "Express",
        "from": "Mumbai CSMT",
        "to": "Amritsar",
        "direction": "DN",
        "days": "Daily",
        "stops": [
          {
            "station": "AGC",
            "arr": "23.45",
            "dep": "23.50"
          },
          {
            "station": "MTJ",
            "arr": "00.30",
            "dep": "00.35"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "02.47"
          },
          {
            "station": "NZM",
            "arr": "03.07",
            "dep": "03.09"
          },
          {
            "station": "NDLS",
            "arr": "03.30",
            "dep": "03.45"
          }
        ]
      },
      {
        "number": "12155",
        "name": "Bhopal Express",
        "from": "Rani Kamlapati",
        "to": "Nizamuddin",
        "direction": "DN",
        "days": "Daily",
        "stops": [
          {
            "station": "AGC",
            "arr": "05.15",
            "dep": "05.17"
          },
          {
            "station": "NZM",
            "arr": "08.00",
            "dep": null
          }
        ]
      },
      {
        "number": "11841",
        "name": "Express",
        "from": "Khajuraho Jn.",
        "to": "Kurukshetra Jn.",
        "direction": "DN",
        "days": "Daily",
        "stops": [
          {
            "station": "AGC",
            "arr": "03.50",
            "dep": "03.55"
          },
          {
            "station": "MTJ",
            "arr": "05.00",
            "dep": "05.05"
          },
          {
            "station": "FDB",
            "arr": null,
            "dep": "07.33"
          },
          {
            "station": "NZM",
            "arr": "08.12",
            "dep": "08.14"
          },
          {
            "station": "NDLS",
            "arr": "08.45",
            "dep": "09.00"
          }
        ]
      },
      {
        "number": "22221",
        "name": "Rajdhani Express",
        "from": "Mumbai CSMT",
        "to": "Nizamudin",
        "direction": "DN",
        "days": "Daily",
        "stops": [
          {
            "station": "AGC",
            "arr": "07.30",
            "dep": "07.32"
          },
          {
            "station": "NZM",
            "arr": "09.55",
            "dep": null
          }
        ]
      },
      {
        "number": "20171",
        "name": "Vande Bharat Express",
        "from": "Rani Kamalapati",
        "to": "Nizamuddin",
        "direction": "DN",
        "days": "Except Sa",
        "stops": [
          {
            "station": "AGC",
            "arr": "11.01",
            "dep": "11.05"
          },
          {
            "station": "NZM",
            "arr": "13.16",
            "dep": null
          }
        ]
      }
    ]
  },
  "possession": {
    "label": "CANDIDATE POSSESSION WINDOW - DERIVED FROM PUBLIC PASSENGER TIMETABLE",
    "rules": {
      "safety_buffer_minutes": 10,
      "minimum_window_minutes": 20,
      "occupancy": "Every section between a train's consecutive (published or interpolated) stops is occupied for the whole leg, extended by the safety buffer at both ends.",
      "windows": "Train-free gaps of at least the minimum window per (track, section); a section any rejected train might have occupied yields no window.",
      "label": "CANDIDATE POSSESSION WINDOW - DERIVED FROM PUBLIC PASSENGER TIMETABLE",
      "coverage_statement": "Timetable source: TAG-2026 (23 trains). Freight, EMU/MEMU and the working timetable are NOT included, so a derived window may overstate free track."
    }
  },
  "works": [
    {
      "demoJobKey": "signal-fdb-pwl",
      "jobType": "SIGNALLING_INTERLOCKING",
      "sectionId": "FDB-PWL",
      "summary": "Strengthening of the UP/DN main-line track circuits, Okhla-Palwal ('A' route), Delhi Division",
      "items": [
        {
          "zone": "NR",
          "itemNo": 1575,
          "page": 193,
          "text": "1575 Strengthening Track Circuit of UP/DN Main  line Okhla - Palwal  of 'A' route in Delhi Division. 15.17 (RRSK 15.17)"
        }
      ]
    },
    {
      "demoJobKey": "ballast-rkm-agc",
      "jobType": "BALLAST_TAMPING",
      "sectionId": "RKM-AGC",
      "summary": "Complete track renewal (33.439 km) and through sleeper renewal (57.810 Tkm), Agra Cantt.-Mathura",
      "items": [
        {
          "zone": "NCR",
          "itemNo": 102,
          "page": 77,
          "text": "102 Agra Cantt.-Mathura - CTR(S) - 33.439 km 56.56 (S.Fund 1.00, RRSK 41.37, R. 4.94, EBR(S) 9.24)"
        },
        {
          "zone": "NCR",
          "itemNo": 110,
          "page": 77,
          "text": "110 Agra Cantt. - Mathura Jn. (UP&DN) - TSR(P) - 57.810 Tkm (PB#523/2023-24/NCR) 71.14 (S.Fund 54.40, RRSK 6.04, R. 10.70)"
        }
      ]
    },
    {
      "demoJobKey": "inspection-mtj-rkm",
      "jobType": "ROUTINE_INSPECTION",
      "sectionId": "MTJ-RKM",
      "summary": "Through rail renewal, Agra-Palwal (66.902 km)",
      "items": [
        {
          "zone": "NCR",
          "itemNo": 115,
          "page": 77,
          "text": "115 Agra-Palwal - TRR(P) - 66.902 kms 89.05 (DRF 38.80, S.Fund 5.00, RRSK 37.46, EBR(S) 7.79)"
        }
      ]
    },
    {
      "demoJobKey": "fracture-mtj-rkm",
      "jobType": "EMERGENCY_REPAIR",
      "sectionId": "MTJ-RKM",
      "summary": "Through rail renewal, Agra-Palwal (66.902 km)",
      "items": [
        {
          "zone": "NCR",
          "itemNo": 115,
          "page": 77,
          "text": "115 Agra-Palwal - TRR(P) - 66.902 kms 89.05 (DRF 38.80, S.Fund 5.00, RRSK 37.46, EBR(S) 7.79)"
        }
      ]
    },
    {
      "demoJobKey": "ohe-rkm-agc",
      "jobType": "OHE_MAINTENANCE",
      "sectionId": "RKM-AGC",
      "summary": "Upgradation of the Electric Traction System, Mathura-Dholpur-Antri (covers Mathura-Agra Cantt.)",
      "items": [
        {
          "zone": "NCR",
          "itemNo": 217,
          "page": 84,
          "text": "217 Mathura-Dholpur-Antri section- Upgradation work of Electric Traction System (NCR) (PB#190/RE/2023-24) 498.89 (Cap. 498.89)"
        }
      ]
    }
  ],
  "worksWording": "GROUNDING: REAL RAILWAY WORK / PROJECT (sanctioned in the 2026-27 budget). The field observation itself is a DEMO MAINTENANCE INPUT: it is not evidence that a defect exists at that location.",
  "blocks": [
    {
      "id": "NR-FDB-2026-09",
      "kind": "POWER_AND_TRAFFIC_BLOCK",
      "location": "Faridabad station, platform lines 4 and 5 (platforms 2 and 3), Hazrat Nizamuddin-Palwal section, Delhi Division",
      "from": "2026-09-01",
      "to": "2026-10-15",
      "status": "IN_PROGRESS (01-09-2026 to 15-10-2026)",
      "class": "REAL_DATED_SNAPSHOT",
      "usedInDerivation": false,
      "note": "A station-yard block on platform lines. It is not a block-section possession on the running lines modelled here."
    },
    {
      "id": "CR-MTJ-2024-01",
      "kind": "NON_INTERLOCKING_WORK_YARD_REMODELLING",
      "location": "Mathura Junction, Agra Division, North Central Railway",
      "from": "2024-01-10",
      "to": "2024-02-07",
      "status": "HISTORICAL",
      "class": "REAL_DATED_SNAPSHOT",
      "usedInDerivation": false,
      "note": "Cancellation periods of individual trains in the notice range from 10-01-2024 to 07-02-2024."
    }
  ],
  "infrastructure": {
    "kmPosts": [
      {
        "place": "Bilochpura",
        "km": 1348.6,
        "asOf": "2025-10-09",
        "class": "REAL_DATED_SNAPSHOT"
      },
      {
        "place": "Runakta",
        "km": 1357.67,
        "asOf": "2025-10-09",
        "class": "REAL_DATED_SNAPSHOT"
      },
      {
        "place": "Kitham",
        "km": 1366.65,
        "asOf": "2025-10-14",
        "class": "REAL_DATED_SNAPSHOT"
      },
      {
        "place": "Farah",
        "km": 1378.15,
        "asOf": "2025-10-14",
        "class": "REAL_DATED_SNAPSHOT"
      },
      {
        "place": "Bad",
        "km": 1386.84,
        "asOf": "2025-10-14",
        "class": "REAL_DATED_SNAPSHOT"
      },
      {
        "place": "Mathura Jn",
        "km": 1397.06,
        "asOf": "2025-10-24",
        "class": "REAL_DATED_SNAPSHOT"
      },
      {
        "place": "Rundhi",
        "km": 1473.981,
        "asOf": "2021-12-03",
        "class": "REAL_DATED_SNAPSHOT"
      },
      {
        "place": "Palwal",
        "km": 1483.291,
        "asOf": "2021-12-03",
        "class": "DERIVED_FROM_REAL"
      },
      {
        "place": "Raja Ki Mandi",
        "km": 1347.15,
        "asOf": "2012-03-20",
        "class": "DERIVED_FROM_REAL"
      },
      {
        "place": "Agra Cantt.",
        "km": 1343.27,
        "asOf": "2012-03-20",
        "class": "DERIVED_FROM_REAL"
      }
    ],
    "runningLines": [
      {
        "location": "Sholaka-Rundhi (block section)",
        "lines": "UP main, DN main, 3rd line, 4th line",
        "count": 4,
        "asOf": "2021-12-03"
      },
      {
        "location": "Kitham / Farah / Bad",
        "lines": "UP main, DN main, 3rd main line",
        "count": 3,
        "asOf": "2025-10-14"
      },
      {
        "location": "Raja Ki Mandi",
        "lines": "UP main, DN main",
        "count": 2,
        "asOf": "2012-03-20"
      }
    ],
    "automaticSignalling": [
      "Bilochpura-Runakta",
      "Runakta-Kitham",
      "Hodal-Sholaka",
      "Sholaka-Rundhi",
      "Rundhi-Palwal"
    ],
    "kavach": [
      {
        "section": "Palwal-Mathura-Nagda (633 route-km)",
        "date": "2025-12-05"
      },
      {
        "section": "Tughlakabad Jn Cabin-Palwal (35 route-km)",
        "date": "2026-01-30"
      }
    ],
    "levelCrossings": 9
  },
  "statement": "Published railway infrastructure and timetable data as an offline, dated reference layer. Possession windows are derived from the public timetable using explicit engineering rules. Maintenance observations are controlled demo inputs grounded in real railway work categories. No live or confidential Indian Railways feed is connected."
} as const;

export type Snapshot = typeof SNAPSHOT;
